hs.addSlideshow(new_cfg(baseConfig, 'laclusaz'));
var config_laclusaz = new_cfg(baseConfig2, 'laclusaz');
hs.addSlideshow(new_cfg(baseConfig, 'redrock'));
var config_redrock = new_cfg(baseConfig2, 'redrock');
hs.addSlideshow(new_cfg(baseConfig, 'sailing'));
var config_sailing = new_cfg(baseConfig2, 'sailing');
hs.addSlideshow(new_cfg(baseConfig, 'poemealoup'));
var config_poemealoup = new_cfg(baseConfig2, 'poemealoup');
hs.addSlideshow(new_cfg(baseConfig, 'ptreyes'));
var config_ptreyes = new_cfg(baseConfig2, 'ptreyes');
hs.addSlideshow(new_cfg(baseConfig, 'shuteye2'));
var config_shuteye2 = new_cfg(baseConfig2, 'shuteye2');
hs.addSlideshow(new_cfg(baseConfig, 'ggsemi'));
var config_ggsemi = new_cfg(baseConfig2, 'ggsemi');
hs.addSlideshow(new_cfg(baseConfig, 'emeraldsdonner'));
var config_emeraldsdonner = new_cfg(baseConfig2, 'emeraldsdonner');
hs.addSlideshow(new_cfg(baseConfig, 'kokopelli'));
var config_kokopelli = new_cfg(baseConfig2, 'kokopelli');
hs.addSlideshow(new_cfg(baseConfig, 'yoclassics'));
var config_yoclassics = new_cfg(baseConfig2, 'yoclassics');
hs.addSlideshow(new_cfg(baseConfig, 'berard'));
var config_berard = new_cfg(baseConfig2, 'berard');
hs.addSlideshow(new_cfg(baseConfig, 'hpointe'));
var config_hpointe = new_cfg(baseConfig2, 'hpointe');
hs.addSlideshow(new_cfg(baseConfig, 'bostan'));
var config_bostan = new_cfg(baseConfig2, 'bostan');
hs.addSlideshow(new_cfg(baseConfig, 'marion2'));
var config_marion2 = new_cfg(baseConfig2, 'marion2');
hs.addSlideshow(new_cfg(baseConfig, 'sierra'));
var config_sierra = new_cfg(baseConfig2, 'sierra');
hs.addSlideshow(new_cfg(baseConfig, 'shuteye'));
var config_shuteye = new_cfg(baseConfig2, 'shuteye');
hs.addSlideshow(new_cfg(baseConfig, 'marion'));
var config_marion = new_cfg(baseConfig2, 'marion');
hs.addSlideshow(new_cfg(baseConfig, 'rouges'));
var config_rouges = new_cfg(baseConfig2, 'rouges');
hs.addSlideshow(new_cfg(baseConfig, 'fairview'));
var config_fairview = new_cfg(baseConfig2, 'fairview');
hs.addSlideshow(new_cfg(baseConfig, 'tahoe'));
var config_tahoe = new_cfg(baseConfig2, 'tahoe');
hs.addSlideshow(new_cfg(baseConfig, 'russell'));
var config_russell = new_cfg(baseConfig2, 'russell');
hs.addSlideshow(new_cfg(baseConfig, 'eastbuttress'));
var config_eastbuttress = new_cfg(baseConfig2, 'eastbuttress');
hs.addSlideshow(new_cfg(baseConfig, 'pinnacles2'));
var config_pinnacles2 = new_cfg(baseConfig2, 'pinnacles2');
hs.addSlideshow(new_cfg(baseConfig, 'yosemite'));
var config_yosemite = new_cfg(baseConfig2, 'yosemite');
hs.addSlideshow(new_cfg(baseConfig, 'grotto'));
var config_grotto = new_cfg(baseConfig2, 'grotto');
hs.addSlideshow(new_cfg(baseConfig, 'mickey'));
var config_mickey = new_cfg(baseConfig2, 'mickey');
hs.addSlideshow(new_cfg(baseConfig, 'machete'));
var config_machete = new_cfg(baseConfig2, 'machete');
hs.addSlideshow(new_cfg(baseConfig, 'quatre_tetes'));
var config_quatre_tetes = new_cfg(baseConfig2, 'quatre_tetes');
hs.addSlideshow(new_cfg(baseConfig, 'pinnacles'));
var config_pinnacles = new_cfg(baseConfig2, 'pinnacles');
hs.addSlideshow(new_cfg(baseConfig, 'cathedral_peak'));
var config_cathedral_peak = new_cfg(baseConfig2, 'cathedral_peak');
hs.addSlideshow(new_cfg(baseConfig, 'royal_arches'));
var config_royal_arches = new_cfg(baseConfig2, 'royal_arches');
hs.addSlideshow(new_cfg(baseConfig, 'tallac'));
var config_tallac = new_cfg(baseConfig2, 'tallac');
hs.addSlideshow(new_cfg(baseConfig, 'tuolumne'));
var config_tuolumne = new_cfg(baseConfig2, 'tuolumne');
hs.addSlideshow(new_cfg(baseConfig, 'whitney'));
var config_whitney = new_cfg(baseConfig2, 'whitney');
hs.addSlideshow(new_cfg(baseConfig, 'shasta'));
var config_shasta = new_cfg(baseConfig2, 'shasta');
hs.addSlideshow(new_cfg(baseConfig, 'moab'));
var config_moab = new_cfg(baseConfig2, 'moab');
